---
- hosts: backend
  become: true
  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - sudo
        state: present

    - name: Install Netdata using official script
      shell: |
        bash -c "curl -L -Ss https://my-netdata.io/kickstart.sh | bash -s -- --non-interactive"
      args:
        creates: /opt/netdata

    - name: Fix permissions on Netdata directory
      file:
        path: /opt/netdata
        state: directory
        recurse: yes
        owner: netdata
        group: netdata

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Netdata service
      systemd:
        name: netdata
        state: started
        enabled: yes
      register: netdata_service
      failed_when: netdata_service.failed and "'ExecStart' in netdata_service.msg"

    - name: Show Netdata logs if service failed
      command: journalctl -xeu netdata.service
      when: netdata_service.failed
      ignore_errors: yes
