---
- hosts: backend
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - git
          - zlib1g-dev
          - uuid-dev
          - libmnl-dev
          - gcc
          - make
          - autoconf
          - pkg-config
          - net-tools
        state: present

    - name: Download Netdata installer script
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/kickstart.sh
        mode: '0755'
        follow_redirects: yes

    - name: Run Netdata installer
      command: bash /tmp/kickstart.sh --stable-channel --non-interactive
      args:
        creates: /opt/netdata/bin/netdata

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Netdata service
      systemd:
        name: netdata
        enabled: yes
        state: started
